server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/service1_db
    username: user1
    password: password1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
