# cat <<EOF > fluentd-config.yaml
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: fluentd-config
#   namespace: logging
#   labels:
#     k8s-app: fluentd
# data:
#   fluent.conf: |
#     @include containers.input.conf
#     @include kubernetes.conf
#     @include systemd.conf

#     <match **>
#       @type elasticsearch
#       host elasticsearch-master.logging.svc
#       port 9200
#       scheme https
#       ssl_verify false
#       user elastic
#       password "#{ENV['FLUENT_ELASTICSEARCH_PASSWORD']}"
#       logstash_format true
#       logstash_prefix fluentd
#       include_tag_key true
#       type_name access_log
#       reconnect_on_error true
#       reload_on_failure true
#       request_timeout 2147483648
#     </match>
# EOF

kubectl create secret generic fluentd-es \
  --from-literal=FLUENT_ELASTICSEARCH_PASSWORD=$(kubectl get secret elasticsearch-master-credentials -n logging -o jsonpath="{.data.password}" | base64 -d) \
  -n logging


# cat <<EOF > fluentd-daemonset.yaml
# apiVersion: apps/v1
# kind: DaemonSet
# metadata:
#   name: fluentd
#   namespace: logging
#   labels:
#     k8s-app: fluentd
# spec:
#   selector:
#     matchLabels:
#       k8s-app: fluentd
#   template:
#     metadata:
#       labels:
#         k8s-app: fluentd
#     spec:
#       serviceAccountName: fluentd
#       tolerations:
#         - key: node-role.kubernetes.io/master
#           operator: Exists
#           effect: NoSchedule
#       containers:
#         - name: fluentd
#           image: fluent/fluentd-kubernetes-daemonset:v1.16.3-debian-elasticsearch7-1.1
#           env:
#             - name: FLUENT_ELASTICSEARCH_PASSWORD
#               valueFrom:
#                 secretKeyRef:
#                   name: fluentd-es
#                   key: FLUENT_ELASTICSEARCH_PASSWORD
#           volumeMounts:
#             - name: config-volume
#               mountPath: /fluentd/etc/fluent.conf
#               subPath: fluent.conf
#             - name: varlog
#               mountPath: /var/log
#             - name: varlibdockercontainers
#               mountPath: /var/lib/docker/containers
#               readOnly: true
#       volumes:
#         - name: config-volume
#           configMap:
#             name: fluentd-config
#         - name: varlog
#           hostPath:
#             path: /var/log
#         - name: varlibdockercontainers
#           hostPath:
#             path: /var/lib/docker/containers
# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: fluentd
#   namespace: logging
# EOF

# kubectl apply -f fluentd-config.yaml
# kubectl apply -f fluentd-daemonset.yaml