apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: logging
  labels:
    k8s-app: fluentd
data:
  fluent.conf: |
    @include containers.input.conf
    @include kubernetes.conf
    @include systemd.conf

    <match **>
      @type elasticsearch
      host elasticsearch-master.logging.svc
      port 9200
      scheme https
      ssl_verify false
      user elastic
      password "#{ENV['FLUENT_ELASTICSEARCH_PASSWORD']}"
      logstash_format true
      logstash_prefix fluentd
      include_tag_key true
      type_name access_log
      reconnect_on_error true
      reload_on_failure true
      request_timeout 2147483648
    </match>
