apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: devops
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      format json
    </source>
    <match kubernetes.**>
      @type elasticsearch
      host elasticsearch.devops.svc.cluster.local
      port 9200
      logstash_format true
      include_tag_key true
      flush_interval 5s
    </match>
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: devops
spec:
  selector:
    matchLabels:
      name: fluentd
  template:
    metadata:
      labels:
        name: fluentd
    spec:
      containers:
        - name: fluentd
          image: fluent/fluentd:v1.14
          volumeMounts:
            - name: config-volume
              mountPath: /fluentd/etc
      volumes:
        - name: config-volume
          configMap:
            name: fluentd-config