expose:
  type: clusterIP
  tls:
    enabled: false

externalURL: http://harbor.local
harborAdminPassword: "Harbor12345"

persistence:
  enabled: true
  persistentVolumeClaim:
    registry:
      storageClass: gp2
      size: 5Gi
    jobservice:
      storageClass: gp2
      size: 1Gi
    database:
      storageClass: gp2
      size: 2Gi
    redis:
      storageClass: gp2
      size: 1Gi
    trivy:
      storageClass: gp2
      size: 1Gi

logLevel: info
