controller:
  image: "jenkins/jenkins:lts"
  tag: ""
  installPlugins:
    - kubernetes:latest
    - workflow-aggregator:latest
    - git:latest
    - configuration-as-code:latest

  adminUser: admin
  adminPassword: admin

  serviceType: NodePort
  nodePort: 32000
  servicePort: 8080

  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"

  serviceAccount:
    create: true
    name: jenkins

  persistence:
    enabled: true
    size: 8Gi

  jenkinsUrl: http://jenkins.devops.svc.cluster.local:8080
  jenkinsHome: /var/jenkins_home

  agent:
    podName: default
    customJenkinsLabels: jenkins-agent
    resources:
      requests:
        cpu: "200m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "1Gi"
    containerTemplate:
      image: jenkins/inbound-agent
      args: "${computer.jnlpmac} ${computer.name}"
      workingDir: "/home/jenkins/agent"
