grafana:
  enabled: false
alertmanager:
  enabled: false
prometheus:
  service:
    type: ClusterIP
    port: 9090
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi

