version: '3.8'

services:
  db1:
    image: postgres
    container_name: db1
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: service1_db
    ports:
      - "5432:5432"
    networks:
      - backend

  db2:
    image: postgres
    container_name: db2
    environment:
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: password2
      POSTGRES_DB: service2_db
    ports:
      - "5433:5432"
    networks:
      - backend

networks:
  backend:
