apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice1
  namespace: app-nonprod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice1
  template:
    metadata:
      labels:
        app: microservice1
    spec:
      containers:
        - name: microservice1
          image: ${{ secrets.DOCKER_USERNAME }}/capstone-microservice1:${TAG}
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: microservice2
  namespace: app-nonprod
spec:
  selector:
    app: microservice2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
