apiVersion: v1
kind: Service
metadata:
  name: microservice2
  namespace: app-nonprod
spec:
  selector:
    app: microservice2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
