apiVersion: apps/v1
kind: Deployment
metadata:
  name: spa
  namespace: app-nonprod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spa
  template:
    metadata:
      labels:
        app: spa
    spec:
      containers:
        - name: spa
          image: ${{ secrets.DOCKER_USERNAME }}/capstone-frontend:${TAG}
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: spa
  namespace: app-nonprod
spec:
  selector:
    app: spa
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
