name: CI/CD - Prod

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/fe.dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/capstone-frontend:${{ github.ref_name }}
          no-cache: true

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
  
      - name: Build microservice1 JAR
        run: mvn clean package -f ./microservice1/pom.xml

      - name: Build microservice2 JAR
        run: mvn clean package -f ./microservice2/pom.xml

      - name: Build and push microservice1
        uses: docker/build-push-action@v5
        with:
          context: ./microservice1
          file: ./microservice1/microservice1.dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/capstone-microservice1:${{ github.ref_name }}
          no-cache: true

      - name: Build and push microservice2
        uses: docker/build-push-action@v5
        with:
          context: ./microservice2
          file: ./microservice2/microservice2.dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/capstone-microservice2:${{ github.ref_name }}
<<<<<<< HEAD
          no-cache: true


=======
          no-cache: true
>>>>>>> hotfix/fix-payment-bug
